# Generated by Django 4.0.1 on 2022-01-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_user_id', models.IntegerField(default=0)),
                ('repo_names', models.JSONField(default='')),
                ('avatar_url', models.TextField(default='')),
                ('fetched_time', models.IntegerField(default=0)),
            ],
        ),
    ]
